---
crio_kubernetes_version: "v1.32"
crio_version: "v1.32"
crio_enable_service: true
crio_start_service: true
crio_disable_swap: true
proxy_enabled: true
proxy_host: ""
proxy_port: 3128

crio_base_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gpg

crio_packages:
  - cri-o
