---
kubeadm_enable_kubelet: true

kubeadm_pod_network_cidr: "10.244.0.0/16"

kubeadm_kubeconfifg_path: /etc/kubernetes/admin.conf

kubeadm_cri_socket: "unix:///var/run/crio/crio.sock"

kubeadm_install_cni: true
kubeadm_cni_url: "https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml"
