---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check kubelet binary
      ansible.builtin.command: kubelet --version
      changed_when: false

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Check CRI-O service is enabled
      ansible.builtin.assert:
        that:
          - ansible_facts.services['crio.service'].status == 'enabled'
